id: A8A3AFACE
base_file: f9D99.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:48:05.276665
  last_modified_at: 2022-06-17 12:48:05.276668
