id: A8A3AFACE
base_file: f2600.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:48:05.208744
  last_modified_at: 2022-06-17 12:48:05.208747
