id: A8A3AFACE
base_file: f6EBE.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:48:05.251046
  last_modified_at: 2022-06-17 12:48:05.251050
