id: A8A3AFACE
base_file: fBF2A.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:48:05.301001
  last_modified_at: 2022-06-17 12:48:05.301004
