id: A8A3AFACE
base_file: fF26F.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:48:05.334180
  last_modified_at: 2022-06-17 12:48:05.334183
