id: A8A3AFACE
base_file: f977E.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:48:05.271896
  last_modified_at: 2022-06-17 12:48:05.271902
