id: A8A3AFACE
base_file: fC6D3.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:48:05.316177
  last_modified_at: 2022-06-17 12:48:05.316180
