id: A8A3AFACE
base_file: fA0FF.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:48:05.283551
  last_modified_at: 2022-06-17 12:48:05.283554
