id: A8A3AFACE
base_file: f6D8F.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:48:05.245697
  last_modified_at: 2022-06-17 12:48:05.245700
