id: A8A3AFACE
base_file: f7513.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:48:05.259122
  last_modified_at: 2022-06-17 12:48:05.259125
