id: A8A3AFACE
base_file: f3A46.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:48:05.217399
  last_modified_at: 2022-06-17 12:48:05.217421
